"""initial lv core

Revision ID: 9ab0a2dea4dd
Revises: 
Create Date: 2026-07-29 13:04:55.378112
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ab0a2dea4dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lv_documents',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('project_public_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('current_draft_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('current_contract_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('tender','estimate','offer','contract','change_order','billing','internal')", name=op.f('ck_lv_documents_kind_allowed')),
    sa.CheckConstraint("status IN ('draft','active','archived')", name=op.f('ck_lv_documents_status_allowed')),
    sa.ForeignKeyConstraint(['current_contract_version_id'], ['lv_versions.id'], name='fk_lv_documents_current_contract_version_id_lv_versions', use_alter=True),
    sa.ForeignKeyConstraint(['current_draft_version_id'], ['lv_versions.id'], name='fk_lv_documents_current_draft_version_id_lv_versions', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lv_documents'))
    )
    with op.batch_alter_table('lv_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lv_documents_project_public_id'), ['project_public_id'], unique=False)
        batch_op.create_index('ix_lv_documents_project_status', ['project_public_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lv_documents_public_id'), ['public_id'], unique=True)

    op.create_table('lv_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('lv_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=250), nullable=True),
    sa.Column('based_on_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_by', sa.String(length=128), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.CheckConstraint("status IN ('draft','in_review','released','contractual','superseded','archived')", name=op.f('ck_lv_versions_status_allowed')),
    sa.ForeignKeyConstraint(['based_on_version_id'], ['lv_versions.id'], name=op.f('fk_lv_versions_based_on_version_id_lv_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lv_document_id'], ['lv_documents.id'], name=op.f('fk_lv_versions_lv_document_id_lv_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lv_versions')),
    sa.UniqueConstraint('lv_document_id', 'version_number', name='uq_lv_versions_document_number')
    )
    with op.batch_alter_table('lv_versions', schema=None) as batch_op:
        batch_op.create_index('ix_lv_versions_document_status', ['lv_document_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lv_versions_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lv_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lv_versions_public_id'))
        batch_op.drop_index('ix_lv_versions_document_status')

    op.drop_table('lv_versions')
    with op.batch_alter_table('lv_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lv_documents_public_id'))
        batch_op.drop_index('ix_lv_documents_project_status')
        batch_op.drop_index(batch_op.f('ix_lv_documents_project_public_id'))

    op.drop_table('lv_documents')
    # ### end Alembic commands ###
